//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenThanhNhan_2121110075
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocGia
    {
        public int SoThe { get; set; }
        public Nullable<int> MaDK { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public Nullable<System.DateTime> HanSD { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayCN { get; set; }
    }
}
