//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenThanhNhan_2121110075
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class saleEntities : DbContext
    {
        public saleEntities()
            : base("name=saleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DocGia> DocGias { get; set; }
        public virtual DbSet<QLMuon> QLMuons { get; set; }
        public virtual DbSet<QLSach> QLSaches { get; set; }
        public System.Data.Entity.DbSet<QLTra> QLTras { get; set; }
        public virtual DbSet<TaiKhoan> TaiKhoans { get; set; }
    }
}
