//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenThanhNhan_2121110075
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLDocGia
    {
        public int MaDocGia { get; set; }
        public string TenDocGia { get; set; }
        public string NgaySinh { get; set; }
        public string MSSV { get; set; }
        public string SoDienThoai { get; set; }
        public string NgayHetHan { get; set; }
    }
}
