//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenThanhNhan_2121110075
{
    using System;
    using System.Collections.Generic;
    
    public partial class QLMuon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QLMuon()
        {
            this.QLTras = new HashSet<QLTra>();
        }
    
        public string maPhieuMuon { get; set; }
        public string maNVMuon { get; set; }
        public string maDocGiaMuon { get; set; }
        public string maTaiLieuMuon { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<System.DateTime> HanTra { get; set; }
        public string maSach { get; set; }
    
        public virtual DocGia DocGia { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual QLSach QLSach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QLTra> QLTras { get; set; }
    }
}
