//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenThanhNhan_2121110075
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public string TenTaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string Email { get; set; }
        public string TenNguoiDung { get; set; }
        public string MaNV { get; set; }
        public string ChucVu { get; set; }
        public string SoDienThoai { get; set; }
    }
}
